apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: artifactory
    labels:
      app: artifactory
  spec:
    selector:
      app: artifactory
    ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
- apiVersion: v1
  kind: Route
  metadata:
    name: artifactory
  spec:
    to:
      kind: Service
      name: artifactory
- apiVersion: v1
  kind: Pod
  metadata:
    name : artifactory
    labels:
      app: artifactory
  spec:
    containers:
    - name: artifactory
      image: mangirdas/artifactory-openshift
      volumMounts:
        - name: artifactory-work
          mountPath: /artifactory
      ports:
      - containerPort: 8080
        protocol: TCP
  volumes:
  - name: artifactory-work
    hostPath:
      path: /vol/artifactory
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: artifactory
    labels:
      app: artifactory
  spec:
    dockerImageRepository: mangirdas/artifactory-openshift
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: artifactory
    name: artifactory
  spec:
    replicas: 1
    selector:
      app: artifactory
      deploymentconfig: artifactory
    template:
      metadata:
        labels:
          app: artifactory
          deploymentconfig: artifactory
      spec:
        containers:
        - name: artifactory
          image: mangirdas/artifactory-openshift
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - artifactory
        from:
          kind: ImageStreamTag
          name: artifactory:latest
